const fs = require("fs");
const path = require("path");
const root = path.resolve(__dirname, "..");
const html = fs.readFileSync(path.join(root, "index.html"), "utf8");
const preview = fs.readFileSync(path.join(root, "preview.html"), "utf8");
const generator = fs.readFileSync(path.join(root, "generator.html"), "utf8");
const generatorApp = fs.readFileSync(path.join(root, "generator.js"), "utf8");
const app = fs.readFileSync(path.join(root, "app.js"), "utf8");
const data = JSON.parse(fs.readFileSync(path.join(root, "report-data.example.json"), "utf8"));
if (!html.includes("generator.html") || !generator.includes("report-json") || !generator.includes("evidence-files") || !generator.includes('id="sample-data"') || !generatorApp.includes("facadefixer-generated-report") || !preview.includes("app.js")) throw new Error("entry point is incomplete");
if (!generatorApp.includes("sampleEvidenceLoaded") || !generatorApp.includes("已载入内置的已批准脱敏示例证据")) throw new Error("sample data must satisfy the evidence precheck");
if (!generatorApp.includes("attachEvidenceImages") || !generatorApp.includes("readAsDataURL")) throw new Error("uploaded evidence images must be embedded in generated reports");
if (!generatorApp.includes("reference_images") || !app.includes("[0, 1, 2, 3]")) throw new Error("each defect must render four evidence image slots");
if (!generator.includes("building_76_reference.html") || !preview.includes("building_76_reference.html")) throw new Error("reference report link is missing");
if (generatorApp.includes('fetch("report-data.example.json")')) throw new Error("sample must work from a local file URL");
if (generator.includes("data-phase=") || generator.includes("flow-help")) throw new Error("unnecessary workflow indicator remains");
if (!app.includes("localStorage.getItem") || !app.includes("window.name")) throw new Error("generated-report cross-page handoff is incomplete");
if (data.schema_version !== "report-document/v1") throw new Error("example must use ReportDocument v1");
if (!app.includes("sign-page") || !app.includes("statement") || !app.includes("detail-title")) throw new Error("reference report layout is incomplete");
if (!app.includes("原始图像") || !app.includes("GPS纬度") || !app.includes("行人风险") || !app.includes("图 ' + number + '-")) throw new Error("defect detail table must match the reference layout");
if (!app.includes("window.print")) throw new Error("A4 print action missing");
const reference = fs.readFileSync(path.join(root, "building_76_reference.html"), "utf8");
if (!reference.includes('id="print-button"') || !reference.includes("window.print")) throw new Error("reference report print action missing");
console.log("report_web static contract passed");

