(function () {
  "use strict";
  var reportRoot = document.getElementById("report");
  var stateLabels = { measured: "正式量测/人工确认", model_estimate: "模型估算（未作为正式量测）", not_collected: "未采集", inaccessible: "不可达", pending_confirmation: "待确认" };
  var categoryLabels = { concrete_crack: "混凝土裂缝", concrete_spalling: "混凝土剥落", rust_stain: "锈迹", water_stain: "水渍", tile_crack: "瓷砖裂缝", tile_spalling: "瓷砖剥落", contaminants: "污染物/附着物" };
  var escapeHtml = function (value) { return String(value == null ? "" : value).replace(/[&<>'"]/g, function (char) { return {"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;","\"":"&quot;"}[char]; }); };
  var label = function (id, labels) { return labels[id] || id || "待补充"; };
  var evidenceHtml = function (item) { var image = item.image_uri ? '<img src="' + escapeHtml(item.image_uri) + '" alt="已批准证据">' : '<div class="evidence-placeholder">证据图片待补充</div>'; return '<article class="evidence">' + image + '<span class="status ' + escapeHtml(item.state) + '">' + escapeHtml(label(item.state, stateLabels)) + '</span><p>' + escapeHtml(item.caption || item.reason || "无补充说明") + '</p><small>来源：' + escapeHtml(item.source) + ' · 期次：' + escapeHtml(item.period) + ' · 版本：' + escapeHtml(item.version) + '</small></article>'; };
  var preflight = function (data) { var missing = []; var responsibility = data.project && data.project.responsibility || {}; ["inspector", "author", "reviewer", "approver"].forEach(function (key) { if (!responsibility[key] || responsibility[key] === "待补充") missing.push(key); }); return missing; };
  var render = function (data) {
    if (!data || data.schema_version !== "report-document/v1") throw new Error("仅支持 report-document/v1 JSON");
    var project = data.project || {}, defects = data.defects || [], missing = preflight(data);
    var counts = defects.reduce(function (result, item) { result[item.severity || "general"] = (result[item.severity || "general"] || 0) + 1; return result; }, {});
    var standards = (project.standards || []).map(function (item) { return '<li>' + escapeHtml(item) + '</li>'; }).join("");
    var instruments = (project.instruments || []).map(function (item, index) { return '<tr><td>' + (index + 1) + '</td><td>' + escapeHtml(item.name) + '</td><td>' + escapeHtml(item.model) + '</td><td>' + escapeHtml(item.asset_id) + '</td></tr>'; }).join("");
    var defectRows = defects.map(function (item, index) { var evidence = item.evidence && item.evidence[0] || {}; return '<tr><td>' + (index + 1) + '</td><td>' + escapeHtml(item.defect_id) + '</td><td>' + escapeHtml(item.building_id) + '</td><td>' + escapeHtml(item.facade_id) + '</td><td>' + escapeHtml(label(item.category_id, categoryLabels)) + '</td><td class="severity ' + escapeHtml(item.severity || "general") + '">' + escapeHtml(label(item.severity || "general", {minor:"轻微",general:"一般",serious:"严重"})) + '</td><td><span class="status ' + escapeHtml(evidence.state) + '">' + escapeHtml(label(evidence.state, stateLabels)) + '</span></td></tr>'; }).join("");
    var details = defects.map(function (item, index) { var evidence = item.evidence || []; return '<article class="defect"><div class="defect-title">缺陷 ' + (index + 1) + ' · ' + escapeHtml(item.defect_id) + ' · ' + escapeHtml(label(item.category_id, categoryLabels)) + '</div><div class="defect-content"><table class="info-table"><tr><td>楼栋</td><td>' + escapeHtml(item.building_id) + '</td><td>立面</td><td>' + escapeHtml(item.facade_id) + '</td></tr><tr><td>严重程度</td><td class="severity ' + escapeHtml(item.severity || "general") + '">' + escapeHtml(label(item.severity || "general", {minor:"轻微",general:"一般",serious:"严重"})) + '</td><td>冻结结论</td><td>' + escapeHtml(item.expert_conclusion && item.expert_conclusion.text || "待补充") + '</td></tr></table><div class="evidence-grid">' + (evidence.length ? evidence.map(evidenceHtml).join("") : '<div class="evidence-placeholder">未提供证据</div>') + '</div></div></article>'; }).join("");
    reportRoot.innerHTML = '<section class="cover"><h1>外墙检测鉴定报告</h1><h2>网页端专业预览版</h2><div class="cover-meta"><p><b>工程名称：</b>' + escapeHtml(project.name) + '</p><p><b>检测期次：</b>' + escapeHtml(project.period) + '</p><p><b>报告版本：</b>' + escapeHtml(data.report_version) + '</p><p><b>冻结时间：</b>' + escapeHtml(data.frozen_at) + '</p></div></section>' +
      '<section class="section"><h1>责任信息与目录</h1>' + (missing.length ? '<div class="notice"><b>尚不能形成正式版本：</b>请补充责任信息：' + missing.map(escapeHtml).join("、") + '。</div>' : '<div class="notice">责任信息完整，可进入正式版本的后续审批流程。</div>') + '<table class="info-table"><tr><td>委托单位</td><td>' + escapeHtml(project.client) + '</td><td>工程地点</td><td>' + escapeHtml(project.location) + '</td></tr><tr><td>现场检测</td><td>' + escapeHtml(project.responsibility && project.responsibility.inspector) + '</td><td>报告编写</td><td>' + escapeHtml(project.responsibility && project.responsibility.author) + '</td></tr><tr><td>报告审核</td><td>' + escapeHtml(project.responsibility && project.responsibility.reviewer) + '</td><td>报告批准</td><td>' + escapeHtml(project.responsibility && project.responsibility.approver) + '</td></tr></table><ol class="toc"><li>工程概况</li><li>检测依据与方法</li><li>主要检测仪器</li><li>楼栋与立面索引</li><li>缺陷汇总表</li><li>逐缺陷证据</li><li>结论与说明</li></ol></section>' +
      '<section class="section"><h1>一、工程概况</h1><p>' + escapeHtml(project.overview || "工程概况待补充") + '</p><h2>二、检测依据与方法</h2><p>' + escapeHtml(project.method || "检测方法待补充") + '</p><p><b>引用标准：</b></p><ol>' + standards + '</ol><h2>三、主要检测仪器</h2><table><thead><tr><th>序号</th><th>仪器名称</th><th>型号</th><th>编号</th></tr></thead><tbody>' + instruments + '</tbody></table></section>' +
      '<section class="section"><h1>四、楼栋与立面索引</h1><p>本网页端预览依据 ReportDocument 中的缺陷归属生成索引；图形索引将由 #130 补充。</p><table><thead><tr><th>楼栋</th><th>立面</th><th>已记录缺陷数</th></tr></thead><tbody>' + Object.keys(defects.reduce(function (acc, item) { var key = item.building_id + "|" + item.facade_id; acc[key] = (acc[key] || 0) + 1; return acc; }, {})).map(function (key) { var parts = key.split("|"); var count = defects.filter(function (item) { return item.building_id === parts[0] && item.facade_id === parts[1]; }).length; return '<tr><td>' + escapeHtml(parts[0]) + '</td><td>' + escapeHtml(parts[1]) + '</td><td>' + count + '</td></tr>'; }).join("") + '</tbody></table><h1>五、缺陷汇总表</h1><table><thead><tr><th>序号</th><th>缺陷编号</th><th>楼栋</th><th>立面</th><th>类别</th><th>严重程度</th><th>证据状态</th></tr></thead><tbody>' + defectRows + '</tbody></table></section>' +
      '<section class="section"><h1>六、逐缺陷证据</h1>' + details + '</section><section class="section"><h1>七、结论与说明</h1><p>当前共记录 ' + defects.length + ' 项缺陷：严重 ' + (counts.serious || 0) + ' 项、一般 ' + (counts.general || 0) + ' 项、轻微 ' + (counts.minor || 0) + ' 项。模型估算、未采集、不可达及待确认数据均不作为正式量测结果。</p><p>本网页为数据预览与复核界面；正式签署、DOCX/PDF 发布和版本存档将由后续报告流程执行。</p><div class="footer"><span>报告 ID：' + escapeHtml(data.report_id) + '</span><span>数据版本：' + escapeHtml(project.source_version) + '</span></div></section>';
  };
  function showError(error) { reportRoot.innerHTML = '<section class="section first"><h1>无法加载报告</h1><div class="notice">' + escapeHtml(error.message) + '</div></section>'; }
  var generated = sessionStorage.getItem("facadefixer-generated-report");
  if (!generated) { try { generated = localStorage.getItem("facadefixer-generated-report"); } catch (ignore) {} }
  if (!generated && window.name.indexOf("facadefixer-generated-report:") === 0) generated = window.name.slice("facadefixer-generated-report:".length);
  if (generated) { try { render(JSON.parse(generated)); } catch (error) { showError(error); } }
  else { fetch("report-data.example.json").then(function (response) { if (!response.ok) throw new Error("示例数据加载失败"); return response.json(); }).then(render).catch(showError); }
  document.getElementById("file-input").addEventListener("change", function (event) { var file = event.target.files[0]; if (!file) return; var reader = new FileReader(); reader.onload = function () { try { render(JSON.parse(reader.result)); } catch (error) { showError(error); } }; reader.readAsText(file, "utf-8"); });
  document.getElementById("print-button").addEventListener("click", function () { window.print(); });
}());

